// 统一主题色定义：可在此文件中直接修改或新增主题
// 与 DaisyUI 配色键保持一致（primary/secondary/accent/neutral/base-100/200/300 等）

const themes = [
  {
    light: {
      primary: "white",
      "primary-focus": "#f5f5f5",
      "primary-content": "black",
      secondary: "#ededed",
      accent: "#b8b8b8",
      neutral: "#ebebeb",
      "base-100": "white",
      "base-200": "#e6e6e6",
      "base-300": "#d9d9d9",
      ".card-title": { "margin-bottom": "0!important" },
    },
    black: {
      primary: "#262626",
      "primary-focus": "#222020",
      secondary: "#343232",
      accent: "#2d2d2d",
      neutral: "#383838",
      "base-100": "black",
      "base-200": "#0d0d0d",
      "base-300": "#2a2a2a",
    },
    config: {
      token: {
        colorPrimary: '#0D9496',
        colorPrimaryBg: '#F0FDFB',
        colorPrimaryBgHover: '#DCFFFC',
        colorPrimaryBorder: '#99F6EE',
        colorPrimaryBorderHover: '#5EEAE2',
        colorPrimaryHover: '#14B8B7',
        colorPrimaryActive: '#0F7376',
        colorPrimaryText: '#0F7376',
        colorPrimaryTextActive: '#115B5E',
        colorPrimaryTextHover: '#14B8B7',
        fontSize: 16,
        colorSuccessBg: '#F2FCED',
        colorSuccessBgHover: '#ADEFAB',
        colorSuccessBorder: '#ADEFAB',
        colorSuccessBorderHover: '#76E174',
        colorSuccessHover: '#19B023',
        colorSuccess: '#0D961B',
        colorSuccessActive: '#1D720A',
        colorSuccessTextHover: '#0D961B',
        colorSuccessText: '#1D720A',
        colorSuccessTextActive: '#105A0B',
        colorWarningBg: '#FFF7EC',
        colorWarningBgHover: '#FFD9A7',
        colorWarningBorder: '#FFD9A7',
        colorWarningBorderHover: '#FFBD70',
        colorWarningHover: '#FF770F',
        colorWarning: '#F15B05',
        colorWarningActive: '#C84306',
        colorWarningText: '#C84306',
        colorWarningTextHover: '#F15B05',
        colorWarningTextActive: '#96320D',
        colorErrorBg: '#FFF0F0',
        colorErrorBgHover: '#FFCAD0',
        colorErrorBorder: '#FFCAD0',
        colorErrorBorderHover: '#FF9FA9',
        colorErrorHover: '#FE3552',
        colorError: '#EC123D',
        colorErrorActive: '#C80833',
        colorErrorText: '#C80833',
        colorErrorTextHover: '#EC123D',
        colorErrorTextActive: '#A70A31',
        colorText: '#04152F',
        colorTextSecondary: '#495366',
        colorTextTertiary: '#636D7E',
        colorTextQuaternary: '#818999',
        colorTextDescription: '#818999',
        colorBorder: '#E0E8ED',
        colorBorderSecondary: '#E0E8ED',
        colorFill: '#E1EAF6',
        colorFillSecondary: '#EAEFF5',
        colorFillTertiary: '#F0F4F9',
        colorFillQuaternary: '#F7FAFF',
        colorBgLayout: '#F7FAFF',
        colorBgSpotlight: 'rgba(4, 21, 47, 0.85)',
        colorBgMask: 'rgba(4, 21, 47, 0.45)',
        colorInfo: '#0d9496',
        colorInfoBg: '#F0FDFB',
        colorInfoBgHover: '#99F6EE',
        colorInfoBorder: '#99F6EE',
        colorInfoBorderHover: '#5EEAE2',
        colorInfoHover: '#14B8B7',
        colorInfoActive: '#0F7376',
        colorInfoText: '#0F7376',
        colorInfoTextHover: '#14B8B7',
        colorInfoTextActive: '#115B5E',
        colorTextBase: '#04152f',
        colorFillAlter: '#F0F5F9',
        colorLink: '#1A7AF8',
        colorLinkHover: '#1A7AF8',
        borderRadiusLG: 8,
        borderRadius: 8,
        marginXS: 16,
        margin: 10,
        marginXXS: 4,
      },
      components: {
        Modal: {
          marginXS: 8,
        },
        Menu: {
          itemMarginInline: 0,
          padding: 10,
          colorItemBgHover: '#F7FAFF',
          colorSubItemBg: 'rgba(0, 0, 0, 0)',
          lineType: 'none',
          colorItemText: '#04152F',
          colorItemTextSelected: '#0F7376',
          controlHeightLG: 48,
          motionEaseInOut: 0,
          motionDurationMid: 10,
        },
        Table: {
          colorFillAlter: '#F0F5F9',
          colorLink: '#1A7AF8',
          colorLinkActive: '#0A5AD1',
          colorLinkHover: '#429AFF',
          colorIcon: '#636D7E',
          colorIconHover: '#04152F',
          colorFillContent: '#E0E8ED',
          colorSplit: '#E0E8ED',
          colorBorderSecondary: '#E0E8ED',
          controlHeight: 40,
          colorTextHeading: '#495366',
          padding: 16,
          paddingContentVerticalLG: 16,
        },
        Button: {
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
          paddingContentHorizontal: 23,
          colorLink: '#1A7AF8',
          colorLinkActive: '#0A5AD1',
          colorLinkHover: '#429AFF',
          controlOutlineWidth: 0,
          marginXS: 8,
        },
        Input: {
          controlHeight: 40,
          controlHeightSM: 32,
          controlHeightLG: 48,
          colorTextPlaceholder: '#AEB9CE',
        },
        InputNumber: {
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
        },
        Mentions: {
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
        },
        Radio: {
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
          controlOutlineWidth: 2,
          padding: 24,
        },
        Select: {
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
          controlHeightXS: 24,
        },
        Slider: {
          colorPrimaryBorder: '#0d9496',
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
        },
        Switch: {
          controlHeight: 40,
        },
        Popconfirm: {
          marginXS: 10,
        },
        Transfer: {
          controlHeight: 40,
          controlHeightLG: 48,
          listWidth: 250,
          listHeight: 270,
          listWidthLG: 320,
        },
        TreeSelect: {
          controlHeightSM: 32,
          controlInteractiveSize: 24,
          paddingXS: 24,
        },
        Calendar: {
          paddingSM: 12,
        },
        DatePicker: {
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
        },
        Pagination: {
          controlHeight: 40,
          controlHeightLG: 48,
          controlHeightSM: 32,
          colorFill: '#fff',
        },
        Dropdown: {
          controlHeight: 40,
        },
        Cascader: {
          controlHeight: 40,
          controlInteractiveSize: 20,
        },
        Checkbox: {
          controlInteractiveSize: 20,
        },
        Tag: {
          fontSizeSM: 16,
          fontSize: 16,
          marginXS: 8,
          paddingXXS: 8,
          lineHeight: 1.75,
        },
        Tree: {
          controlHeightSM: 32,
          controlInteractiveSize: 20,
          paddingXS: 8,
        },
        Anchor: {
          padding: 16,
          paddingXXS: 4,
        },
        Card: {
          fontSize: 14,
          paddingLG: 24,
          padding: 18,
          paddingXS: 16,
          borderRadiusLG: 16,
        },
        Form: {
          controlHeight: 40,
          colorTextHeading: '#495366',
        },
        Descriptions: {
          padding: 24,
          marginXS: 0,
        },
        Popover: {
          fontSize: 14,
        },
        Steps: {
          controlHeightLG: 60,
          paddingLG: 32,
          fontSizeLG: 16,
          fontSize: 14,
          colorTextDescription: '#04152F',
          controlItemBgActive: '#E6F5FF',
        },
        WdTable: {
          borderRadiusLG: 16,
          paddingLG: 24,
          margin: 16,
          colorFillAlter: '#F0F5F9',
          padding: 20,
          tablePageMargin: 8,
          colorBgContainer: '#ffffff',
          tablePaddingBottom: 0,
          paginationTopPadding: 8,
          paginationBottomPadding: 24,
          paginationLeft: 264,
          paginationBottom: 16,
          tablePadding: 0,
          paginationZIndex: 2,
          paginationRight: 40,
          paginationRightPadding: 0,
        },
        WdImage: {
          fontSize: 16,
          borderRadius: 16,
          colorBorder: '#E0E8ED',
        },
        WdBread: {
          margin: 16,
          borderRadiusLG: 16,
          padding: 24,
        },
        Breadcrumb: {
          marginXS: 12,
        },
        ContentCard: {
          contentCardTitlePadding: 24,
        },
        Affix: {
          zIndexBase: 2,
        },
      },
    }
    // 示例：自定义一个新主题（可按需启用）
    // emerald: {
    //   primary: "#10b981",
    //   "primary-focus": "#059669",
    //   secondary: "#064e3b",
    //   accent: "#047857",
    //   neutral: "#0f172a",
    //   "base-100": "#0b1020",
    //   "base-200": "#0a0e1a",
    //   "base-300": "#09101a",
    // },
  },
];

export default themes;